export type ProviderTemplate = {
  id: string;
  label: string;
  baseUrl: string;
  category: string;
  modelsEndpoint?: string;
  websiteUrl?: string;
  signupUrl?: string;
};

export const RECOMMENDED_PROVIDER_TEMPLATE_IDS = [
  "groq",
  "xingchen",
  "longcat",
  "zai",
  "gitee",
] as const;

export const PROVIDER_TEMPLATES: ProviderTemplate[] = [
  {
    id: "openai",
    label: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    category: "Official",
    modelsEndpoint: "/models",
    websiteUrl: "https://platform.openai.com",
    signupUrl: "https://platform.openai.com/signup",
  },
  {
    id: "custom",
    label: "Custom API",
    baseUrl: "",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    category: "Official",
    modelsEndpoint: "/models",
    websiteUrl: "https://openrouter.ai",
    signupUrl: "https://openrouter.ai/keys",
  },
  {
    id: "groq",
    label: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    category: "Official",
    modelsEndpoint: "/models",
    websiteUrl: "https://groq.com",
    signupUrl: "https://console.groq.com/keys",
  },
  {
    id: "xai",
    label: "xAI",
    baseUrl: "https://api.x.ai/v1",
    category: "Official",
    modelsEndpoint: "/models",
    websiteUrl: "https://x.ai",
    signupUrl: "https://console.x.ai",
  },
  {
    id: "anthropic",
    label: "Anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    category: "Official",
    modelsEndpoint: "/models",
    websiteUrl: "https://www.anthropic.com",
    signupUrl: "https://console.anthropic.com",
  },
  {
    id: "gemini",
    label: "Gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    category: "Official",
    modelsEndpoint: "/models",
    websiteUrl: "https://ai.google.dev",
    signupUrl: "https://aistudio.google.com/apikey",
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://www.deepseek.com",
    signupUrl: "https://platform.deepseek.com/sign_up",
  },
  {
    id: "together",
    label: "Together AI",
    baseUrl: "https://api.together.xyz/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://www.together.ai",
    signupUrl: "https://api.together.ai/signin",
  },
  {
    id: "fireworks",
    label: "Fireworks AI",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://fireworks.ai",
    signupUrl: "https://fireworks.ai/login",
  },
  {
    id: "siliconflow",
    label: "SiliconFlow",
    baseUrl: "https://api.siliconflow.com/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://siliconflow.cn",
    signupUrl: "https://cloud.siliconflow.cn/account/ak",
  },
  {
    id: "zai",
    label: "Z.AI",
    baseUrl: "https://api.z.ai/api/paas/v4",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://z.ai",
    signupUrl: "https://z.ai",
  },
  {
    id: "gitee",
    label: "Gitee AI",
    baseUrl: "https://ai.gitee.com/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://ai.gitee.com",
    signupUrl: "https://ai.gitee.com/dashboard/settings/tokens",
  },
  {
    id: "minimax",
    label: "MiniMax",
    baseUrl: "https://api.minimaxi.com/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://www.minimaxi.com",
    signupUrl:
      "https://platform.minimaxi.com/user-center/basic-information/interface-key",
  },
  {
    id: "moonshot",
    label: "Moonshot",
    baseUrl: "https://api.moonshot.cn/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://www.moonshot.cn",
    signupUrl: "https://platform.moonshot.cn/console/api-keys",
  },
  {
    id: "perplexity",
    label: "Perplexity",
    baseUrl: "https://api.perplexity.ai",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://www.perplexity.ai",
    signupUrl: "https://docs.perplexity.ai/guides/getting-started",
  },
  {
    id: "qwen",
    label: "Qwen",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://help.aliyun.com/zh/model-studio",
    signupUrl: "https://bailian.console.aliyun.com/#/api-key",
  },
  {
    id: "stepfun",
    label: "StepFun",
    baseUrl: "https://api.stepfun.com/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://www.stepfun.com",
    signupUrl: "https://platform.stepfun.com/interface-key",
  },
  {
    id: "doubao",
    label: "Doubao",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://www.volcengine.com/product/doubao",
    signupUrl: "https://console.volcengine.com/ark",
  },
  {
    id: "baichuan",
    label: "Baichuan",
    baseUrl: "https://api.baichuan-ai.com/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://www.baichuan-ai.com",
    signupUrl: "https://platform.baichuan-ai.com/console/apikey",
  },
  {
    id: "ollama",
    label: "Ollama",
    baseUrl: "http://localhost:11434/v1",
    category: "Local",
    modelsEndpoint: "/models",
    websiteUrl: "https://ollama.com",
  },
  {
    id: "lmstudio",
    label: "LM Studio",
    baseUrl: "http://localhost:1234/v1",
    category: "Local",
    modelsEndpoint: "/models",
    websiteUrl: "https://lmstudio.ai",
  },
  {
    id: "localai",
    label: "LocalAI",
    baseUrl: "http://localhost:8080/v1",
    category: "Local",
    modelsEndpoint: "/models",
    websiteUrl: "https://localai.io",
  },
  {
    id: "vllm",
    label: "vLLM",
    baseUrl: "http://localhost:8000/v1",
    category: "Local",
    modelsEndpoint: "/models",
    websiteUrl: "https://docs.vllm.ai",
  },
  {
    id: "xinference",
    label: "Xinference",
    baseUrl: "http://localhost:9997/v1",
    category: "Local",
    modelsEndpoint: "/models",
    websiteUrl: "https://inference.readthedocs.io",
  },
  {
    id: "omlx",
    label: "oMLX",
    baseUrl: "http://localhost:8000/v1",
    category: "Local",
    modelsEndpoint: "/models",
    websiteUrl: "https://github.com/nickam/omlx",
  },
  {
    id: "xingchen",
    label: "讯飞星辰",
    baseUrl: "https://maas-api.cn-huabei-1.xf-yun.com/v2",
    category: "Official",
    modelsEndpoint: "/models",
    websiteUrl: "https://maas.xfyun.cn",
    signupUrl: "https://maas.xfyun.cn/modelService",
  },
  {
    id: "zhipu",
    label: "Bigmodel",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://open.bigmodel.cn",
    signupUrl: "https://open.bigmodel.cn/usercenter/apikeys",
  },
  {
    id: "longcat",
    label: "LongCat",
    baseUrl: "https://api.longcat.chat/openai",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
    websiteUrl: "https://longcat.chat",
    signupUrl: "https://longcat.chat/platform/api_keys",
  },
  {
    id: "apple_intelligence",
    label: "Apple Intelligence",
    baseUrl: "apple-intelligence://",
    category: "Local",
  },
];
