export type ProviderTemplate = {
  id: string;
  label: string;
  baseUrl: string;
  category: string;
  modelsEndpoint?: string;
};

export const RECOMMENDED_PROVIDER_TEMPLATE_IDS = [
  "groq",
  "xingchen",
  "longcat",
  "zai",
  "gitee",
] as const;

export const PROVIDER_TEMPLATES: ProviderTemplate[] = [
  {
    id: "openai",
    label: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    category: "Official",
    modelsEndpoint: "/models",
  },
  {
    id: "custom",
    label: "Custom API",
    baseUrl: "",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    category: "Official",
    modelsEndpoint: "/models",
  },
  {
    id: "groq",
    label: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    category: "Official",
    modelsEndpoint: "/models",
  },
  {
    id: "xai",
    label: "xAI",
    baseUrl: "https://api.x.ai/v1",
    category: "Official",
    modelsEndpoint: "/models",
  },
  {
    id: "anthropic",
    label: "Anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    category: "Official",
    modelsEndpoint: "/models",
  },
  {
    id: "gemini",
    label: "Gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    category: "Official",
    modelsEndpoint: "/models",
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "together",
    label: "Together AI",
    baseUrl: "https://api.together.xyz/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "fireworks",
    label: "Fireworks AI",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "siliconflow",
    label: "SiliconFlow",
    baseUrl: "https://api.siliconflow.com/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "zai",
    label: "Z.AI",
    baseUrl: "https://api.z.ai/api/paas/v4",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "gitee",
    label: "Gitee AI",
    baseUrl: "https://ai.gitee.com/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "minimax",
    label: "MiniMax",
    baseUrl: "https://api.minimaxi.com/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "moonshot",
    label: "Moonshot",
    baseUrl: "https://api.moonshot.cn/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "perplexity",
    label: "Perplexity",
    baseUrl: "https://api.perplexity.ai",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "qwen",
    label: "Qwen",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "stepfun",
    label: "StepFun",
    baseUrl: "https://api.stepfun.com/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "doubao",
    label: "Doubao",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "baichuan",
    label: "Baichuan",
    baseUrl: "https://api.baichuan-ai.com/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "ollama",
    label: "Ollama",
    baseUrl: "http://localhost:11434/v1",
    category: "Local",
    modelsEndpoint: "/models",
  },
  {
    id: "lmstudio",
    label: "LM Studio",
    baseUrl: "http://localhost:1234/v1",
    category: "Local",
    modelsEndpoint: "/models",
  },
  {
    id: "localai",
    label: "LocalAI",
    baseUrl: "http://localhost:8080/v1",
    category: "Local",
    modelsEndpoint: "/models",
  },
  {
    id: "vllm",
    label: "vLLM",
    baseUrl: "http://localhost:8000/v1",
    category: "Local",
    modelsEndpoint: "/models",
  },
  {
    id: "xinference",
    label: "Xinference",
    baseUrl: "http://localhost:9997/v1",
    category: "Local",
    modelsEndpoint: "/models",
  },
  {
    id: "omlx",
    label: "oMLX",
    baseUrl: "http://localhost:8000/v1",
    category: "Local",
    modelsEndpoint: "/models",
  },
  {
    id: "xingchen",
    label: "讯飞星辰",
    baseUrl: "https://maas.xfyun.cn/v1",
    category: "Official",
    modelsEndpoint: "/models",
  },
  {
    id: "zhipu",
    label: "Bigmodel",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "longcat",
    label: "LongCat",
    baseUrl: "https://api.longcat.ai/v1",
    category: "OpenAI Compatible",
    modelsEndpoint: "/models",
  },
  {
    id: "apple_intelligence",
    label: "Apple Intelligence",
    baseUrl: "apple-intelligence://",
    category: "Local",
  },
];
