import {
  Box,
  Button,
  Dialog,
  Flex,
  Kbd,
  Text,
  TextArea,
} from "@radix-ui/themes";
import { IconCheck, IconLoader2, IconSparkles } from "@tabler/icons-react";
import { invoke } from "@tauri-apps/api/core";
import { type as osType } from "@tauri-apps/plugin-os";
import React, { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { useSettings } from "../../../../hooks/useSettings";
import {
  formatKeyCombination,
  type OSType,
} from "../../../../lib/utils/keyboard";

type StepStatus = "pending" | "in_progress" | "completed" | "error";

interface PipelineStep {
  label: string;
  status: StepStatus;
}

interface SkillMetadata {
  name: string;
  icon: string;
}

export interface AutoGenerateResult {
  instructions: string;
  name: string;
  icon: string;
  description: string;
}

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onComplete: (result: AutoGenerateResult) => void;
}

export const AutoGenerateDialog: React.FC<AutoGenerateDialogProps> = ({
  open,
  onOpenChange,
  onComplete,
}) => {
  const { t, i18n } = useTranslation();
  const { getSetting } = useSettings();
  const [rawInput, setRawInput] = useState("");
  const [isRunning, setIsRunning] = useState(false);

  // Derive the user's global transcription shortcut
  const transcribeShortcut = useMemo(() => {
    const bindings = getSetting("bindings") || {};
    const binding = bindings["transcribe"];
    if (!binding?.current_binding) return null;
    const detectedOs: OSType = (() => {
      try {
        const t = osType();
        if (t === "macos") return "macos";
        if (t === "windows") return "windows";
        if (t === "linux") return "linux";
        return "unknown";
      } catch {
        return "unknown";
      }
    })();
    return formatKeyCombination(binding.current_binding, detectedOs);
  }, [getSetting]);

  const [steps, setSteps] = useState<PipelineStep[]>([
    {
      label: t("settings.postProcessing.prompts.autoGenerate.step1"),
      status: "pending",
    },
    {
      label: t("settings.postProcessing.prompts.autoGenerate.step2"),
      status: "pending",
    },
    {
      label: t("settings.postProcessing.prompts.autoGenerate.step3"),
      status: "pending",
    },
  ]);
  const [errorStep, setErrorStep] = useState<number | null>(null);
  // Store intermediate results for retry
  const [polishedInstructions, setPolishedInstructions] = useState<
    string | null
  >(null);
  const [metadata, setMetadata] = useState<SkillMetadata | null>(null);

  const updateStep = (index: number, status: StepStatus) => {
    setSteps((prev) =>
      prev.map((s, i) => (i === index ? { ...s, status } : s)),
    );
  };

  const resetSteps = () => {
    setSteps([
      {
        label: t("settings.postProcessing.prompts.autoGenerate.step1"),
        status: "pending",
      },
      {
        label: t("settings.postProcessing.prompts.autoGenerate.step2"),
        status: "pending",
      },
      {
        label: t("settings.postProcessing.prompts.autoGenerate.step3"),
        status: "pending",
      },
    ]);
    setErrorStep(null);
    setPolishedInstructions(null);
    setMetadata(null);
  };

  const runPipeline = async (startFrom = 0) => {
    setIsRunning(true);
    setErrorStep(null);

    try {
      // Step 1: Polish instructions
      let instructions = polishedInstructions;
      if (startFrom <= 0) {
        updateStep(0, "in_progress");
        instructions = await invoke<string>("optimize_text_with_llm", {
          text: rawInput,
        });
        setPolishedInstructions(instructions);
        updateStep(0, "completed");
      }

      // Step 2: Generate name + icon
      let meta = metadata;
      if (startFrom <= 1) {
        updateStep(1, "in_progress");
        meta = await invoke<SkillMetadata>("generate_skill_metadata", {
          instructions: instructions!,
          locale: i18n.language,
        });
        setMetadata(meta);
        updateStep(1, "completed");
      }

      // Step 3: Generate description
      updateStep(2, "in_progress");
      const description = await invoke<string>("generate_skill_description", {
        name: meta!.name,
        instructions: instructions!,
        locale: i18n.language,
      });
      updateStep(2, "completed");

      // All done — callback with results
      onComplete({
        instructions: instructions!,
        name: meta!.name,
        icon: meta!.icon,
        description,
      });
    } catch (e) {
      console.error("Auto-generate pipeline failed:", e);
      const failedStep = steps.findIndex((s) => s.status === "in_progress");
      if (failedStep >= 0) {
        updateStep(failedStep, "error");
        setErrorStep(failedStep);
      }
      toast.error(String(e));
    } finally {
      setIsRunning(false);
    }
  };

  const handleStart = () => {
    if (!rawInput.trim()) {
      toast.error(t("settings.postProcessing.prompts.autoGenerate.emptyInput"));
      return;
    }
    resetSteps();
    runPipeline(0);
  };

  const handleRetry = () => {
    if (errorStep !== null) {
      runPipeline(errorStep);
    }
  };

  const handleClose = () => {
    if (!isRunning) {
      setRawInput("");
      resetSteps();
      onOpenChange(false);
    }
  };

  const StepIcon: React.FC<{ status: StepStatus }> = ({ status }) => {
    switch (status) {
      case "completed":
        return <IconCheck size={14} className="text-green-500" />;
      case "in_progress":
        return <IconLoader2 size={14} className="animate-spin text-blue-500" />;
      case "error":
        return (
          <Text size="1" color="red">
            !
          </Text>
        );
      default:
        return (
          <Text size="1" color="gray">
            ○
          </Text>
        );
    }
  };

  const showProgress = steps.some((s) => s.status !== "pending");

  return (
    <Dialog.Root open={open} onOpenChange={handleClose}>
      <Dialog.Content maxWidth="500px">
        <Dialog.Title>
          {t("settings.postProcessing.prompts.autoGenerate.title")}
        </Dialog.Title>
        <Dialog.Description size="2" color="gray" mb="4">
          <Box>
            {t("settings.postProcessing.prompts.autoGenerate.description")}
          </Box>
          <Flex align="center" gap="1" mt="1">
            <Text size="1" color="gray">
              {t("settings.postProcessing.prompts.autoGenerate.shortcutHint")}
            </Text>
            {transcribeShortcut && <Kbd size="1">{transcribeShortcut}</Kbd>}
          </Flex>
        </Dialog.Description>

        <Flex direction="column" gap="4">
          {/* Input area */}
          <TextArea
            value={rawInput}
            onChange={(e) => setRawInput(e.target.value)}
            placeholder={t(
              "settings.postProcessing.prompts.autoGenerate.placeholder",
            )}
            rows={6}
            disabled={isRunning}
          />

          {/* Progress display */}
          {showProgress && (
            <Flex
              direction="column"
              gap="2"
              className="rounded-lg bg-gray-50 dark:bg-gray-900 p-3"
            >
              {steps.map((step, i) => (
                <Flex key={i} gap="2" align="center">
                  <StepIcon status={step.status} />
                  <Text
                    size="2"
                    color={step.status === "error" ? "red" : undefined}
                  >
                    {step.label}
                  </Text>
                </Flex>
              ))}
            </Flex>
          )}
        </Flex>

        <Flex gap="3" mt="4" justify="end">
          <Dialog.Close>
            <Button variant="soft" color="gray" disabled={isRunning}>
              {t("common.cancel")}
            </Button>
          </Dialog.Close>
          {errorStep !== null ? (
            <Button onClick={handleRetry} loading={isRunning}>
              {t("common.retry")}
            </Button>
          ) : (
            <Button
              onClick={handleStart}
              disabled={!rawInput.trim()}
              loading={isRunning}
            >
              <IconSparkles size={16} />
              {t("settings.postProcessing.prompts.autoGenerate.start")}
            </Button>
          )}
        </Flex>
      </Dialog.Content>
    </Dialog.Root>
  );
};
