import { Box, Text } from "@radix-ui/themes";
import { useTranslation } from "react-i18next";
import { useEffect, useRef, useState } from "react";
import { useTaskClusters } from "../hooks/useTaskClusters";
import { useSummaryStore } from "../stores/summaryStore";
import { ClusterCard } from "../cluster/ClusterCard";
import { ClusterDetailDrawer } from "../cluster/ClusterDetailDrawer";
import { SplitClusterDialog } from "../cluster/SplitClusterDialog";
import { MergeClusterDialog } from "../cluster/MergeClusterDialog";
import { DeleteClusterConfirm } from "../cluster/DeleteClusterConfirm";
import type { TaskCluster } from "../summaryTypes";

interface DayViewProps {
  onNavigateToHistory: (entryId: number) => void;
}

export function DayView({ onNavigateToHistory }: DayViewProps) {
  const { t } = useTranslation();
  const { selectedDate, expandedClusterIds, toggleClusterExpanded } =
    useSummaryStore();
  const {
    clusters,
    loading,
    generating,
    generate,
    updateField,
    split,
    merge,
    remove,
  } = useTaskClusters(selectedDate);

  const [splitTarget, setSplitTarget] = useState<TaskCluster | null>(null);
  const [mergeTarget, setMergeTarget] = useState<TaskCluster | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<TaskCluster | null>(null);

  // Auto-generate once per date if cache is empty after initial load.
  const autoGeneratedRef = useRef<Set<string>>(new Set());
  useEffect(() => {
    if (
      !loading &&
      !generating &&
      clusters.length === 0 &&
      !autoGeneratedRef.current.has(selectedDate)
    ) {
      autoGeneratedRef.current.add(selectedDate);
      void generate(false);
    }
  }, [loading, generating, clusters.length, selectedDate, generate]);

  if (loading) {
    return (
      <Text size="2" color="gray">
        {t("common.loading")}
      </Text>
    );
  }
  if (generating && clusters.length === 0) {
    return (
      <Text size="2" color="gray">
        {t("settings.summary.dayView.aiGenerating")}
      </Text>
    );
  }
  if (clusters.length === 0) {
    return (
      <Box className="text-center py-12">
        <Text size="3" color="gray">
          {t("settings.summary.dayView.noTranscriptsToday")}
        </Text>
      </Box>
    );
  }

  return (
    <Box>
      <Text size="2" weight="medium" mb="2">
        {t("settings.summary.dayView.todayClusters", {
          count: clusters.length,
        })}
      </Text>
      {clusters.map((c) => (
        <ClusterCard
          key={c.id}
          cluster={c}
          expanded={expandedClusterIds.has(c.id)}
          onToggleExpanded={() => toggleClusterExpanded(c.id)}
          onUpdateField={(field, value) => updateField(c.id, field, value)}
          onOpenSplit={() => setSplitTarget(c)}
          onOpenMerge={() => setMergeTarget(c)}
          onOpenDelete={() => setDeleteTarget(c)}
          detailSlot={
            <ClusterDetailDrawer
              cluster={c}
              onNavigateToHistory={onNavigateToHistory}
            />
          }
        />
      ))}

      <SplitClusterDialog
        open={splitTarget !== null}
        cluster={splitTarget}
        onCancel={() => setSplitTarget(null)}
        onConfirm={async (extractIds, newTitle, extractedDurationMs) => {
          if (!splitTarget) return;
          await split(
            splitTarget.id,
            extractIds,
            newTitle,
            extractedDurationMs,
          );
        }}
      />
      <MergeClusterDialog
        open={mergeTarget !== null}
        targetCluster={mergeTarget}
        otherClusters={clusters}
        onCancel={() => setMergeTarget(null)}
        onConfirm={async (sourceIds) => {
          if (!mergeTarget) return;
          await merge(mergeTarget.id, sourceIds);
        }}
      />
      <DeleteClusterConfirm
        open={deleteTarget !== null}
        clusterTitle={deleteTarget?.title ?? ""}
        onCancel={() => setDeleteTarget(null)}
        onConfirm={async () => {
          if (!deleteTarget) return;
          await remove(deleteTarget.id);
          setDeleteTarget(null);
        }}
      />
    </Box>
  );
}
